
class Constants:
    PEDESTRIAN_MMOC = 0
    PEDESTRIAN_NEIGHBORHOOD = 1
    PEDESTRIAN_VOLUME = 2
    
    BORDER_NONE = -1
    BORDER_NAIVE = 0
    BORDER_NEXT_VOLUME = 1
    BORDER_CUSTOM_IMPLEMENTATION = 2
    BORDER_SURROUNDING_VOLUMES = 3
