class Constants:
    NO_PEDESTRIANS = -1
    PEDESTRIAN_MMOC = 0
    PEDESTRIAN_NEIGHBORHOOD = 1
    
    BORDER_NONE = -1
    BORDER_NAIVE = 0
    CORRIDOR_ONLY = 1
    BORDER_CUSTOM_IMPLEMENTATION = 2
    BORDER_SURROUNDING_VOLUMES = 3
